{% set name = "pastel" %}
{% set version = "0.1.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "bf3b1901b2442ea0d8ab9a390594e5b0c9584709d543a3113506fe8b28cbace3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pastel

about:
  home: https://github.com/sdispater/pastel
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Bring colors to your terminal.
  description: "Pastel is a simple library to help you colorize strings in your terminal."
  doc_url: https://pypi.org/project/pastel/
  dev_url: https://github.com/sdispater/pastel

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
